{{- if ne .Values.memberlist.enable true }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: consul-sidekick
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  resources:
  - pods
  - replicasets
  verbs:
  - get
  - list
  - watch
{{- end }}
