apiVersion: v1
kind: Service
metadata:
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: consul
  name: {{ include "loki-helm.consul" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: consul-server
    port: 8300
    targetPort: 8300
  - name: consul-serf
    port: 8301
    targetPort: 8301
  - name: consul-client
    port: 8400
    targetPort: 8400
  - name: consul-api
    port: 8500
    targetPort: 8500
  - name: statsd-exporter-http-metrics
    port: 8000
    targetPort: 8000
  - name: consul-exporter-http-metrics
    port: 9107
    targetPort: 9107
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: consul
