{{- if ne .Values.memberlist.enable true }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "loki-helm.consul" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: consul
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: consul
  template:
    metadata:
      annotations:
        consul-hash: 5778cd539088c126eed973ed617144e1
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels: {{- include "loki-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: consul
    spec:
      {{- if .Values.consul.affinity }}
      affinity: {{- toYaml .Values.consul.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 16 }}
                app.kubernetes.io/component: consul
            topologyKey: kubernetes.io/hostname
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.consul.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.consul.tolerations | nindent 8 }}
      containers:
      - args:
        - agent
        - -ui
        - -server
        - -client=0.0.0.0
        - -config-file=/etc/config/consul-config.json
        - -bootstrap-expect=1
        env:
        - name: CHECKPOINT_DISABLE
          value: "1"
        image: {{ .Values.consul.image }}
        imagePullPolicy: {{ .Values.consul.pullPolicy | quote }}
        name: consul
        ports:
        - containerPort: 8300
          name: server
        - containerPort: 8301
          name: serf
        - containerPort: 8400
          name: client
        - containerPort: 8500
          name: api
        {{- if .Values.consul.resources }}
        resources: {{- toYaml .Values.consul.resources | nindent 12 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/config
          name: consul
      - args:
        - --namespace=$(POD_NAMESPACE)
        - --pod-name=$(POD_NAME)
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: weaveworks/consul-sidekick:master-f18ad13
        imagePullPolicy: IfNotPresent
        name: sidekick
        volumeMounts:
        - mountPath: /etc/config
          name: consul
      - args:
        - --web.listen-address=:8000
        - --statsd.mapping-config=/etc/config/mapping
        image: prom/statsd-exporter:v0.12.2
        imagePullPolicy: IfNotPresent
        name: statsd-exporter
        ports:
        - containerPort: 8000
          name: http-metrics
        volumeMounts:
        - mountPath: /etc/config
          name: consul
      - args:
        - --consul.server=localhost:8500
        - --web.listen-address=:9107
        - --consul.timeout=1s
        image: prom/consul-exporter:v0.5.0
        imagePullPolicy: IfNotPresent
        name: consul-exporter
        ports:
        - containerPort: 9107
          name: http-metrics
        volumeMounts:
        - mountPath: /etc/config
          name: consul
      serviceAccount: consul-sidekick
      volumes:
      - configMap:
          name: {{ include "loki-helm.consul" . }}
        name: consul
{{- end }}