{{ if .Values.gateway.ingress.enabled }}
{{- $fullName := include "loki-helm.gateway" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{ end }}
kind: Ingress
metadata: 
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  {{- with .Values.gateway.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.gateway.ingress.tls }}
  tls:
  {{- range .Values.gateway.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.gateway.ingress.host }}
      http:
        paths:
          - path: /*
            backend:
              serviceName: {{ $fullName }}
              servicePort: http
{{ end }}