apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-helm.gateway" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  ports:
  - name: nginx-http
    port: 80
    targetPort: 80
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
