apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki-helm.querier-frontend" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: querier-frontend
spec:
  clusterIP: None
  ports:
  - name: querier-frontend-http-metrics
    port: 3100
    targetPort: 3100
  - name: querier-frontend-grpc
    port: 9095
    targetPort: 9095
  selector: {{- include "loki-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: querier-frontend
