apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "loki-helm.memcached-frontend" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "loki-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached-frontend
  {{- if .Values.annotations }}
  annotations:
  {{- toYaml .Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.memcachedFrontend.replicaCount }}
  selector:
    matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: memcached-frontend
  serviceName: {{ include "loki-helm.memcached-frontend" . }}
  template:
    metadata:
      labels: {{- include "loki-helm.labels" . | nindent 8 }}
        app.kubernetes.io/component: memcached-frontend
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.memcachedFrontend.affinity }}
      affinity: {{- toYaml .Values.memcachedFrontend.affinity | nindent 8 }}
      {{- else }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels: {{- include "loki-helm.selectorLabels" . | nindent 16 }}
                app.kubernetes.io/component: memcached-frontend
            topologyKey: kubernetes.io/hostname
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.memcachedFrontend.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.memcachedFrontend.tolerations | nindent 8 }}
      containers:
      - args:
        - -m 1024
        - -I 5m
        - -c 1024
        - -v
        image: {{ .Values.memcached.image }}
        imagePullPolicy: {{ .Values.memcached.pullPolicy | quote }}
        name: memcached
        ports:
        - containerPort: 11211
          name: client
        {{- if .Values.memcachedFrontend.resources }}
        resources: {{- toYaml .Values.memcachedFrontend.resources | nindent 12 }}
        {{- end }}
      - args:
        - --memcached.address=localhost:11211
        - --web.listen-address=0.0.0.0:9150
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        name: exporter
        ports:
        - containerPort: 9150
          name: http-metrics
  updateStrategy:
    type: RollingUpdate
